services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      # e.g. write /bytestash for a domain such as my.domain/bytestash, leave blank in every other case
      - BASE_PATH=
      # the jwt secret used by the server, make sure to generate your own secret token to replace this one
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.nhan23TF0qyO4l4rDMkJ8ebNLMgV62NGfBozt9huymA
      # how long the token lasts, examples: "2 days", "10h", "7d", "1m", "60s"
      - TOKEN_EXPIRY=24h
      # is this bytestash instance open to new accounts being created?
      - ALLOW_NEW_ACCOUNTS=true
    volumes:
      - ./data:/data/snippets