services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    environment:
      - NODE_ENV=production
      - PORT=8500
      - OUTPUT_DIR=/data/snippets
    volumes:
      - ./data:/data/snippets