services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - BASE_PATH=/bytestash
    volumes:
      - ./data:/data/snippets