name: Feature Request
description: Suggest a new idea for the project
title: "[FEATURE] "
labels: enhancement
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Description
        Please provide a detailed description of the feature you would like to see.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      placeholder: "What is the feature you want to propose?"

  - type: input
    id: use_case
    attributes:
      label: Use Case
      placeholder: "How would this feature be used?"

  - type: input
    id: benefits
    attributes:
      label: Benefits
      placeholder: "What are the benefits of implementing this feature?"

  - type: input
    id: alternatives
    attributes:
      label: Alternatives
      placeholder: "Are there any alternative solutions or features?"

  - type: checkboxes
    id: labels
    attributes:
      label: Labels
      options:
        - label: Enhancement
          value: enhancement
        - label: Discussion
          value: discussion
