name: Build and Push Docker Image for Pull Request Testing

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jordan-dalby/bytestash-dev

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag for testing
        id: docker_tag
        run: echo "TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push Docker image for Testing
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}

      - name: Comment on PR with Docker image tag
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const imageTag = process.env.TAG;
            const commentBody = `Test Docker image pushed: \`${imageTag}\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
