name: Build and Push Docker Image for Pull Request Testing

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jordan-dalby/bytestash-dev

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag with PR number
        id: docker_tag
        run: echo "TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Build and Push Docker image for Testing
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}