name: Build Docker Image for Pull Request Testing

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jordan-dalby/bytestash

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker tag for testing
        id: docker_tag
        run: echo "TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image (without push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.TAG }}

      - name: Comment on PR with Docker image tag
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const imageTag = process.env.TAG;
            const commentBody = `Docker image built for testing: \`${imageTag}\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
